### PR TITLE
Create URLClassLoader for plugins loaded from jar file

### PR DESCRIPTION
**Pull request by TheDarkSword**
# Description
This commit addresses the issue where, if you load more than one plugin, the files in the resources (such as plugin.yml and config.yml) are always the same as those of the application undergoing testing. This way, external JARs are loaded using a URLClassLoader, and when a call to #getResourceAsStream is made, the resource is first searched for internally within the JAR and then in the parent (opposite to the default behavior).

Issue reference: https://github.com/MockBukkit/MockBukkit/issues/928

# Checklist
The following items should be checked before the pull request can be merged.
- [x] Code follows existing style.
- [x] Unit tests added (if applicable).

### CODE REVIEW

**Comment by Thorinwasher** [comment]
Sorry for not responding sooner. I mainly just don't consider myself qualified enough for this.

Have you tested the changes, does it work?

Is it possible to remove reduntant code in MockBukkitConfiguredPluginClassLoader, which is used to load jar files?

Except for this, I don's see any issues. Again sorry for neglecting this PR

**Comment by TheDarkSword** [comment]
> Sorry for not responding sooner. I mainly just don't consider myself qualified enough for this.
> 
> Have you tested the changes, does it work?
> 
> Is it possible to remove reduntant code in MockBukkitConfiguredPluginClassLoader, which is used to load jar files?
> 
> Except for this, I don's see any issues. Again sorry for neglecting this PR

Oh, no problem!
So, basically, the issue itself is that by default the ClassLoader first checks if the parent ClassLoader (in our case, it's our plugin) already has that file/class loaded, for example, the config.yml, and then it obtains the one already loaded.
Obviously, that's not the correct file. What I did is simply reverse the normal process, first looking for the resource within the jar itself and then trying to find it by calling the parent ClassLoader.
This way, I managed to test and everything works as it should.
I'll remove the code that is no longer needed from the MockBukkitConfiguredPluginClassLoader class, as you instructed. I'll do that as soon as possible!

**Comment by thelooter** [comment]
> > Sorry for not responding sooner. I mainly just don't consider myself qualified enough for this.
> > Have you tested the changes, does it work?
> > Is it possible to remove reduntant code in MockBukkitConfiguredPluginClassLoader, which is used to load jar files?
> > Except for this, I don's see any issues. Again sorry for neglecting this PR
> 
> Oh, no problem! So, basically, the issue itself is that by default the ClassLoader first checks if the parent ClassLoader (in our case, it's our plugin) already has that file/class loaded, for example, the config.yml, and then it obtains the one already loaded. Obviously, that's not the correct file. What I did is simply reverse the normal process, first looking for the resource within the jar itself and then trying to find it by calling the parent ClassLoader. This way, I managed to test and everything works as it should. I'll remove the code that is no longer needed from the MockBukkitConfiguredPluginClassLoader class, as you instructed. I'll do that as soon as possible!

Would it be possible to create a Method that loads an arbitrary specified config file too? This would allow us to create Integration Tests with custom config files, something thats required by many plugins

**Comment by TheDarkSword** [comment]
@thelooter In the coming days, I will try to find a way. However, the simplest way to do it currently is to modify the config and load it directly into the JAR file.

**Comment by thelooter** [comment]
@TheDarkSword we need some Unit Tests to get this merged. Can you add those?

**Comment by seeseemelk** [comment]
> @TheDarkSword we need some Unit Tests to get this merged. Can you add those?

There is already an `extra/TestPlugin` directly which will be built into a jar file. You might be able to use this jar file in your test.

**Comment by thelooter** [comment]
@TheDarkSword is there anything missing from you're point of view?

**Comment by Thorinwasher** [comment]
As this PR is dormant, I will self assign myself this issue. I guess adding tests for this?

**Review by thelooter — APPROVED** [review]

**Pull request merged**
