### PR TITLE
[ADD] Add support for Bukkit.getServicesManager() (Minecraft 1.15)

### PR DESCRIPTION
**Pull request by 0ddlyoko**
# Description
Add support for Bukkit.getServicesManager() method

# Checklist
The following items should be checked before the pull request can be merged.
- [ ] Version number updated in `settings.gradle`.
- [x] Unit tests added.
- [x] Code follows existing code format.

Version number isn't in file settings.gradle

### CODE REVIEW

**Comment by 0ddlyoko** [comment]
Should I add support for Minecraft 1.14 & lower ?

**Comment by seeseemelk** [comment]
We're not really actively back-porting features to older version of Minecraft as we haven't really gotten any requests from anyone to do so. However, we do keep try to keep our infrastructure set up so that we can easily back port features if we need to.

**Comment by seeseemelk** [comment]
> However, we do keep try to keep our infrastructure set up so that we can easily back port features if we need to.

And looking at our current infrastructure, I'm pretty sure we broke it somewhat recently...
I'll merge it in case it helps someone, but I don't think this will end up Maven central.

**Comment by 0ddlyoko** [comment]
> > However, we do keep try to keep our infrastructure set up so that we can easily back port features if we need to.
> 
> And looking at our current infrastructure, I'm pretty sure we broke it somewhat recently...
> I'll merge it in case it helps someone, but I don't think this will end up Maven central.

I was trying to cherry pick the commit to Minecraft 1.14 but I got some conflicts and the test took a long time to run

**Comment by seeseemelk** [comment]
Hmm, it seems our builds are not being executed for the `v1.15`. This is probably because we moved from Travis CI to GitHub actions very recently, and this branch has not yet been configured for that. Until that is fixed, this PR will sadly not be built automatically.

**Comment by 0ddlyoko** [comment]
Okay, no problem, I just need it for Minecraft 1.16 :)

**Comment by Vinetos** [comment]
> Hmm, it seems our builds are not being executed for the `v1.15`. This is probably because we moved from Travis CI to GitHub actions very recently, and this branch has not yet been configured for that. Until that is fixed, this PR will sadly not be built automatically.

What do you need exactly ? Actually, the github Actions are triggered only on 1.16 branch

**Comment by seeseemelk** [comment]
Some GitHub actions are being executed as of #182, so we should be able to merge it now.

**Pull request merged**
