### PR TITLE
Impl fixed rate scheduler

### PR DESCRIPTION
**Pull request by NeumimTo**
# Description
Implements FoliaAsyncCheduler runAtFixedRate

# Checklist
The following items should be checked before the pull request can be merged.
- [ x] Code follows existing style.
- [ x] Unit tests added (if applicable).

### CODE REVIEW

**Review by thelooter — DISMISSED** [review]
LGTM

**Comment by thelooter** [comment]
Please change your Git Name and Email to reflect your information. Here's some information on how to do that

[Setting Name and Email](https://docs.github.com/en/get-started/getting-started-with-git/setting-your-username-in-git)
[Changing Name and Email on Commits 1](https://stackoverflow.com/questions/8824971/how-to-amend-older-git-commit)
[Changing Name and Email on Commits 2](https://www.git-tower.com/learn/git/faq/change-author-name-email)

**Comment by NeumimTo** [comment]
> Please change your Git Name and Email to reflect your information. Here's some information on how to do that
> 
> [Setting Name and Email](https://docs.github.com/en/get-started/getting-started-with-git/setting-your-username-in-git) [Changing Name and Email on Commits 1](https://stackoverflow.com/questions/8824971/how-to-amend-older-git-commit) [Changing Name and Email on Commits 2](https://www.git-tower.com/learn/git/faq/change-author-name-email)

No

**Comment by thelooter** [comment]
Given you're unwillingness to change your name to something that reflects your Identity, we are gonna reject you're PR for now

**Pull request closed without merging**
