### PR TITLE
PlayerMock.simulatePlayerMove fix for teleportation in PlayerMoveEvent

### PR DESCRIPTION
**Pull request by wuza8**
# Description
This small rearrange of code fixes event execution. 

# Checklist
The following items should be checked before the pull request can be merged.
- [x] Version number updated in `settings.gradle`.
- [x] Unit tests added.
- [x] Code follows existing code format.

# Info on creating a pull request
Before the pull request can be accepted, the version number stored in settings.gradle should be updated.
MockBukkit uses semantic-versioning (https://semver.org/)

 - If the PR fixes a bug in MockBukkit, update the patch version. (if the current version is `0.4.1`, the new version should be `0.4.2`)
 - If the PR adds a new feature to MockBukkit, update minor version. (if the current version is `0.4.1`, the new version should be `0.5.0`)
 - Make sure that unit tests are added which test the relevant changes.
 - Make sure that the changes follow the existing code format.

Note that a PR that fixes an `UnimplementedOperationException` should be considered a new version and not a bugfix.

The version number can be found in `settings.gradle`.

### CODE REVIEW

**Comment by TheBusyBiscuit** [comment]
You didn't actually explain what this fixes though.

**Comment by wuza8** [comment]
Before when PlayerMoveEvent listener would teleport a Player, Player would not be teleported when event would not be cancelled and if event would be cancelled, he would be teleported. This fixes it how it should be - when event would be not canceled Player would be teleported, if event would be canceled player would not be teleported.

**Comment by wuza8** [comment]
So when we have a PlayerMoveEvent listener in our plugin, that does a teleportation inside like this one
```java @EventHandler
			public void onPlayerMove(PlayerMoveEvent event){
                                ...
                                if( blockPlayerSteppedOn.getType().equals(Material.DIRT))
				    event.getPlayer().teleport(teleportLocation);
                                ...
			} 
```
Now what we want to accomplish with a code like this is for example is when a player steps on a dirt block we want to teleport player somewhere and it works in normal bukkit like this.

But because of a false arrangement of player teleportation in simulatePlayerMove method we get to this kind of a code execution:

- player.simulatePlayerMove(simulatingLocation) is invoked
- simulatingLocation gets into event.getTo()
- simulatePlayerMove invokes PlayerMoveEvent
- it looks like player stands on a DIRT block, so player gets teleported to our special location
- simulatePlayerMove gets executed event with setCancelled = false
- !!!because of setCancelled == false simulatePlayerMove SETS PLAYER LOCATION TO event.getTo() THAT IS simulatingLocation SO TELEPORTATION GETS LOST ;C!!!

And that's not how bukkit works...

After this fix the execution of simulatePlayerMove goes like this:

- player.simulatePlayerMove(simulatingLocation) is invoked
- simulatingLocation gets into event.getTo()
- simulatePlayerMove SETS LOCATION OF PLAYER - player.setLocation(simulatingLocation)
- simulatePlayerMove invokes PlayerMoveEvent
- it looks like player stands on a DIRT block, so player gets teleported to our special location
- simulatePlayerMove gets executed event with setCancelled = false
- because of setCancelled == false simulatePlayerMove DOES NOT SET LOCATION OF PLAYER to simulatingLocation

After some tests made with real Bukkit I've come to a conclusion that's how it works and this fix makes that small change

If we would be going with event.setCancelled(true) scenario, the teleportation invoked in PlayerMoveEvent listener would be cancelled by invoking player.setLocation(event.getFrom()) and that also goes like that in Bukkit.

**Comment by wuza8** [comment]
@TheBusyBiscuit Fixed lack of explanation.

**Review by seeseemelk — APPROVED** [review]

**Pull request merged**
