### PR TITLE
Run JaCoCo tasks on test

### PR DESCRIPTION
**Pull request by spscally**
# Description
Updating `build.gradle` so that the JaCoCo report is generated when you run the `test` task. (See: https://docs.gradle.org/current/userguide/jacoco_plugin.html#sec:jacoco_getting_started) If this was intentionally configured this way, feel free to disregard 😄

# Checklist
The following items should be checked before the pull request can be merged.
- [ ] Unit tests added.
- [ ] Code follows existing code format.

# Info on creating a pull request
- Make sure that unit tests are added which test the relevant changes.
- Make sure that the changes follow the existing code format.

# For maintainer
When a PR is approved, the maintainer should label this PR with `release/*`.

- If the PR fixes a bug in MockBukkit, update the patch version. (if the current version is `0.4.1`, the new version should be `0.4.2`)
- If the PR adds a new feature to MockBukkit, update minor version. (if the current version is `0.4.1`, the new version should be `0.5.0`)

Note that a PR that fixes an `UnimplementedOperationException` should be considered a new version and not a bugfix.

### CODE REVIEW

**Comment by seeseemelk** [comment]
The `test` task should just simply run the test and nothing more.
The `check` task however is meant more to run all the verification tasks. It's this task that should probably be invoking `jacocoTestReport`.

It's good that the `jacocoTestReport` task depends on the `test` task. It makes little sense to generate a report without actually running the tests.

So I would probably change it a little so that the dependencies go:

`check` dependsOn `jacocoTestReport` dependsOn `test`.

**Comment by spscally** [comment]
> The `test` task should just simply run the test and nothing more. The `check` task however is meant more to run all the verification tasks. It's this task that should probably be invoking `jacocoTestReport`.
> 
> It's good that the `jacocoTestReport` task depends on the `test` task. It makes little sense to generate a report without actually running the tests.
> 
> So I would probably change it a little so that the dependencies go:
> 
> `check` dependsOn `jacocoTestReport` dependsOn `test`.

Sounds good and thanks for the feedback! I can make that change

**Comment by spscally** [comment]
I'm just going to re-open since I messed up the merge 😅

**Comment by spscally** [comment]
Moved to #669

**Pull request closed without merging**
