### PR TITLE
Fix constructor call

### PR DESCRIPTION
**Pull request by JonnyMc94**
# Description
Address #900 .

The constructor call for BlockDamageEvent has been updated. A small update to a Javadoc has also been made. 

# Checklist
The following items should be checked before the pull request can be merged.
- [X] Code follows existing style.

### CODE REVIEW

**Comment by thelooter** [comment]
This currently doesn't compile, since the `Block#getFace(Block)` Method expects an argument. I'm not super shure if we need the Face here, or if we need to adapt the method / add an Overload to account for Blockfaces

**Comment by JonnyMc94** [comment]
> This currently doesn't compile, since the `Block#getFace(Block)` Method expects an argument. I'm not super shure if we need the Face here, or if we need to adapt the method / add an Overload to account for Blockfaces

Could you give some guidance as to how we would call the constructor without having one of the parameters please?

**Comment by thelooter** [comment]
@Insprill can you please take a look at this

**Comment by Thorinwasher** [comment]
> Could you give some guidance as to how we would call the constructor without having one of the parameters please?

The method `PlayerMock#simulateBlockDamagePure()` is simply lacking enough informaation, it would need to also be given the blockface that the player has damaged the block on. To add the `BlockFace` parameter into the constructor of `BlockDamageEvent`, we would either need to:
- Default to a facing, i.e. BlockFace.EAST (or maybe better BlockFace.SELF)
- Add a duplicate method that has the facing as a parameter

**Review by 4everTheOne — APPROVED** [review]
Looks good to me

**Pull request merged**
