### PR TITLE
Move classes to org.mockbukkit.mockbukkit package

### PR DESCRIPTION
**Pull request by thelooter**
# Description
Moves all classes into the new Package

# Checklist
The following items should be checked before the pull request can be merged.
- [x] Code follows existing style.
- [x] Unit tests added (if applicable).

### CODE REVIEW

**Review by Insprill — CHANGES_REQUESTED** [review]
Conflicts 😊

**Comment by thelooter** [comment]
Not building currently

**Comment by seeseemelk** [comment]
I fixed the build

**Review by Insprill — APPROVED** [review]
LGTM

**Pull request merged**
