### PR TITLE
[WIP] Make it Spotless!

### PR DESCRIPTION
**Pull request by nicolube**
# Description

Basically code style enforcement and formatting

 Sadly I have not found a way to enforce bracers on if, whole for etc statements

# Checklist
The following items should be checked before the pull request can be merged.
- [x] Code follows existing style.
- [x] Unit tests added (if applicable).

### CODE REVIEW

**Comment by nicolube** [comment]
This is just a nice to have. It does not rly change anything

**Comment by Insprill** [comment]
Did you read any of these changes? Most of them either make the code hard to read or don't adhere to our standards. We have a very strict `.editorconfig` file with our code style, although it only works in IntelliJ, and it looks like you're using Eclipse. We make code-style PRs very infrequently since we try to catch these issues during reviews, and since they're usually a waste of time for everyone involved, *especially* when they're done wrong.

**Comment by nicolube** [comment]
I would not dismiss this PR compleatly, I found it hard to fully match a formatter to ur codestyle. 

There are also a few things that are just a bit strage, this repo has some unused imports, and is some places spaces insted of tabs.

Let me tweak the first commit a bit more, maybe we can make it so that the it matches the style better, or just checks for some basic stuff, like unused imports.

**Comment by thelooter** [comment]
Hey @nicolube can you reopen a Pull request with these changes so we can properly evaluate them

**Comment by nicolube** [comment]
@thelooter Almost all changes are just syntax changes, I got the changes to be less by tweaking the eclipse config file, but it is not enough to not change a lot.

**Comment by nicolube** [comment]
Also I'm not allwoed to reopen...

**Pull request closed without merging**
