### PR TITLE
Rename build.properties to mockbukkit.properties

### PR DESCRIPTION
**Pull request by Insprill**
# Description
The current build info file, `build.properties`, will get overridden if a project has its own file under the same name. This simply renames it to `mockbukkit.properties` to ensure there are no conflicts.

# Checklist
The following items should be checked before the pull request can be merged.
- [ ] Unit tests added.
- [x] Code follows existing code format.

# Info on creating a pull request
- Make sure that unit tests are added which test the relevant changes.
- Make sure that the changes follow the existing code format.

# For maintainer
When a PR is approved, the maintainer should label this PR with `release/*`.

- If the PR fixes a bug in MockBukkit, update the patch version. (if the current version is `0.4.1`, the new version should be `0.4.2`)
- If the PR adds a new feature to MockBukkit, update minor version. (if the current version is `0.4.1`, the new version should be `0.5.0`)

Note that a PR that fixes an `UnimplementedOperationException` should be considered a new version and not a bugfix.

### CODE REVIEW

**Review by thelooter — APPROVED** [review]

**Comment by thelooter** [comment]
@MockBukkit/maintainers Can we get a review on this?

**Review by TheBusyBiscuit — COMMENTED** [review]
I don't really know what to say to this.
To me this change is not really useful but I get the idea.

Only concern is that `.properties` usually implies configuration options and `mockbukkit.properties` could signal "this is the place to configure your mockbukkit installation".
Perhaps this is too far-fetched but something like "build data", "metadata" or "build metadata", e.g. "mockbukkit_buildmeta.properties" or similar would make more sense semantically.

Anyway, this use case does not concern me anyway, so this is in no way a rejection or approval, just my thoughts.

**Comment by Insprill** [comment]
That is a fair point. The point of the rename was to reduce the chance of conflicts, and i can see a potential conflict/point of confusion here. It doesn't even need to end with `.properties`, perhaps something like `mockbukkit.metadata` would be better?

**Comment by Insprill** [comment]
Closing since #693 removes this entirely.

**Pull request closed without merging**
