### PR TITLE
V1.15. Added more implementation for MockChunk behaviour

### PR DESCRIPTION
**Pull request by DanikVitek**
# Description
State the changes of the pull request here.

# Checklist
The following items should be checked before the pull request can be merged.
- [x] Unit tests added.
- [x] Code follows existing code format.

# Info on creating a pull request
- Make sure that unit tests are added which test the relevant changes.
- Make sure that the changes follow the existing code format.

# For maintainer
When a PR is approved, the maintainer should label this PR with `release/*`.

- If the PR fixes a bug in MockBukkit, update the patch version. (if the current version is `0.4.1`, the new version should be `0.4.2`)
- If the PR adds a new feature to MockBukkit, update minor version. (if the current version is `0.4.1`, the new version should be `0.5.0`)

Note that a PR that fixes an `UnimplementedOperationException` should be considered a new version and not a bugfix.

### CODE REVIEW

**Comment by thelooter** [comment]
Please make sure the Code is formatted in the Projects Codestyle. Most IDEs should do that automatically according to our EditorConfig. After that I will approve the CI Run

**Comment by DanikVitek** [comment]
the codespace may be deleted soon. Would this be looked into?

**Comment by thelooter** [comment]
> the codespace may be deleted soon. Would this be looked into?

The issue we have is that we don't know why the Action is hanging. Thats why we are currently unable to review this PR. This goes for any Backporting changes at the moment.

**Comment by thelooter** [comment]
Closed since we don't provide support to pre v1.18

**Pull request closed without merging**
