### PR TITLE
Use command map instead of command array and other minor improvements

### PR DESCRIPTION
**Pull request by nowtryz**
# Description

## Use `CommandMap`
I know a lot of command frameworks work with the `CommandMap` to dynamically introduce commands to bukkit. Though MockBukkit was only using its command array.
Hence this PR changes calls to `PluginManagerMock.getCommands` to `MockCommandMap.getCommand`.

## Player list's name
As easy as it seems, I add the implementation for getter and setter of the player list's name

## Console sender
As the console must always be considered op, I updated the getter for the console as well as its name.

## `getKiller` and `setHealth`
I added an implementation for the `getKiller` method in `LivingEntity` and refactor the death logic so every entity can override the death behavior.

# Checklist
The following items should be checked before the pull request can be merged.
- [x] Version number updated in `settings.gradle`.
- [x] Unit tests added.
- [x] Code follows existing code format.

# Info on creating a pull request
Before the pull request can be accepted, the version number stored in settings.gradle should be updated.
MockBukkit uses semantic-versioning (https://semver.org/)

 - If the PR fixes a bug in MockBukkit, update the patch version. (if the current version is `0.4.1`, the new version should be `0.4.2`)
 - If the PR adds a new feature to MockBukkit, update minor version. (if the current version is `0.4.1`, the new version should be `0.5.0`)
 - Make sure that unit tests are added which test the relevant changes.
 - Make sure that the changes follow the existing code format.

Note that a PR that fixes an `UnimplementedOperationException` should be considered a new version and not a bugfix.

The version number can be found in `settings.gradle`.

### CODE REVIEW

**Review by TheBusyBiscuit — COMMENTED** [review]
Please update the version in `settings.gradle` too, should be a minor bump (+ 0.0.1)

**Comment by nowtryz** [comment]
> Please update the version in `settings.gradle` too, should be a minor bump (+ 0.0.1)

Yep I forgot on the previous commit, sorry. But with the new commit, It would be a minor bump instead of a patch right?

**Comment by TheBusyBiscuit** [comment]
You broadened out the scope a lot here.
I dont think this counts as a patch (`0.0.1`) anymore, the version should probably be bumped by a minor release (`0.1.0`) instead.

Though I suggest you look into working with branches and splitting up these features into multiple branches and pull requests.
It would also make it a lot easier for us to review changes in small batches rather than multiple different things at once.

**Comment by nowtryz** [comment]
No problem, I'will split it into multiple PRs

**Comment by nowtryz** [comment]
Closing in favor to #174, #175, #176 and #177.

**Pull request closed without merging**
