### PR TITLE
Switch to Kotlin DSL

### PR DESCRIPTION
**Pull request by Insprill**
# Description
Switch to Kotlin DSLs for Gradle.

# Checklist
The following items should be checked before the pull request can be merged.
- [x] Code follows existing code format.

# Info on creating a pull request
- Make sure that unit tests are added which test the relevant changes.
- Make sure that the changes follow the existing code format.

# For maintainer
When a PR is approved, the maintainer should label this PR with `release/*`.

- If the PR fixes a bug in MockBukkit, update the patch version. (if the current version is `0.4.1`, the new version should be `0.4.2`)
- If the PR adds a new feature to MockBukkit, update minor version. (if the current version is `0.4.1`, the new version should be `0.5.0`)

Note that a PR that fixes an `UnimplementedOperationException` should be considered a new version and not a bugfix.

### CODE REVIEW

**Review by thelooter — APPROVED** [review]

**Comment by md5sha256** [comment]
> Switch to Kotlin DSLs for Gradle. A way to automatically update the project name isn't implemented yet, if anyone has any ideas on how to accomplish this please let me know.

You can do `rootProject.name = "MockBukkit-" + extensions.extraProperties.get("paper.api.version")` in the `settings.gradle.kts`. I tested it locally and it seems to work

**Comment by seeseemelk** [comment]
Don't forget to switch the `extra/TestPlugin` project too

**Review by seeseemelk — CHANGES_REQUESTED** [review]
`extra/TestPlugin` should be converted too

**Comment by Insprill** [comment]
> You can do `rootProject.name = "MockBukkit-" + extensions.extraProperties.get("paper.api.version")` in the `settings.gradle.kts`. I tested it locally and it seems to work

That works, thank you!

**Review by seeseemelk — APPROVED** [review]

**Pull request merged**
