### PR TITLE
Add automation to validate checkstyle 

### PR DESCRIPTION
**Pull request by 4everTheOne**
# Description
This pull requests adds a checkstyle file to the project and also automates style validation in new PR.

Related to issue #890.

# Checklist
The following items should be checked before the pull request can be merged.
- [X] Code follows existing style.
- [X] Unit tests added (if applicable).

### CODE REVIEW

**Comment by 4everTheOne** [comment]
Example of build with checkstyle violations can be found at:
https://github.com/MockBukkit/MockBukkit/actions/runs/8024746287/job/21923925755
https://github.com/MockBukkit/MockBukkit/actions/runs/8025471390/job/21926188322

Example of build without checkstyle violation can be found at:
https://github.com/MockBukkit/MockBukkit/actions/runs/8025655966/job/21926736378

**Comment by 4everTheOne** [comment]
The commit [fc7db61](https://github.com/MockBukkit/MockBukkit/pull/977/commits/fc7db61cf2b97af259672f5c1cf5d9715814179b) was only needed to test this issue while pipeline was failing. This can be reverted when stubs are implemented.

**Comment by thelooter** [comment]
We might wanna use something like the Push Checkstyle Report Action to get annotations in the diff about violations
https://github.com/marketplace/actions/push-checkstyle-report

**Comment by 4everTheOne** [comment]
Hi @thelooter , thank you for you feedback. I attempted to use the action, but this requires additional permissions for the workflow to write the feedback: https://github.com/MockBukkit/MockBukkit/actions/runs/8057005574/job/22007227919#step:9:15

Do you prefer this way?

Here's an example of this implementation in my private repo:
image

**Comment by 4everTheOne** [comment]
At the moment, the build is failing due to the missing permission mentioned here.

> Hi @thelooter , thank you for you feedback. I attempted to use the action, but this requires additional permissions for the workflow to write the feedback: https://github.com/MockBukkit/MockBukkit/actions/runs/8057005574/job/22007227919#step:9:15
> 
> Do you prefer this way?
> 
> Here's an example of this implementation in my private repo: image

If we want to integrate checkstyle without using the github action, we just need to revert the changes done at ".github/workflows/publish.yml".

**Comment by thelooter** [comment]
I don't think anyone is opposed to using the action. It's just that the complete team is doing this as volunteers, and we don't have much time as is, so this hasn't been a high priority, so it hasn't been dealt with. I can't provide a timeframe, but we'll try to look at this as soon as we can feasibly do

**Comment by 4everTheOne** [comment]
@thelooter this is the error we have, when uploading the files:
image

https://github.com/MockBukkit/MockBukkit/actions/runs/10882497616/job/30193664149?pr=977

**Comment by 4everTheOne** [comment]
This should only be merged after:
- https://github.com/MockBukkit/MockBukkit/pull/1150

**Comment by 4everTheOne** [comment]
Replaced by https://github.com/MockBukkit/MockBukkit/pull/1200

**Pull request closed without merging**
