### PR TITLE
Backport #534 and #316 to 1.16

### PR DESCRIPTION
**Pull request by Insprill**

### CODE REVIEW

**Review by thelooter — APPROVED** [review]

**Comment by Hokkaydo** [comment]
Any idea when this will get merged ? I really need it :sweat_smile:

**Comment by thelooter** [comment]
> Any idea when this will get merged ? I really need it sweat_smile

One of the required Actions is stuck. As soon as that is fixed I will merge it

**Comment by Hokkaydo** [comment]
> > Any idea when this will get merged ? I really need it sweat_smile
> 
> One of the required Actions is stuck. As soon as that is fixed I will merge it

Uh okay thanks, and why does it fail ? I tried to figure out myself but I can't understand. It has a release/* label doesn'it ? The check isn't even launched

**Comment by Insprill** [comment]
Because it doesn't exit on the 1.16 branch so GitHub is doing something weird

**Comment by Hokkaydo** [comment]
Arh sad

**Comment by Hokkaydo** [comment]
Any update ? 😇
I know I spam but can I do something to help ?

**Comment by Insprill** [comment]
Unfortunately no. Waiting on @seeseemelk to backport the GitHub actions.

**Comment by Hokkaydo** [comment]
Hellooo, still no update ?

**Comment by thelooter** [comment]
No support for old branches

**Pull request closed without merging**
