### PR TITLE
Implement ServerMock#getCurrentTick

### PR DESCRIPTION
**Pull request by Insprill**
# Description
Implements `ServerMock#getCurrentTick`.

Normally this returns `MinecraftServer.currentTick` which increments each tick, but since our only concept of ticking is the scheduler, we just return its current tick. 

# Checklist
The following items should be checked before the pull request can be merged.
- [x] Code follows existing style.
- [x] Unit tests added (if applicable).

### CODE REVIEW

**Comment by thelooter** [comment]
> Normally this returns `MinecraftServer.currentTick` which increments each tick, but since our only concept of ticking is the scheduler, we just return its current tick.

What about introducing a Tick System? This would give us a cleaner way to start implementing Things like Physics too, and gives us a cleaner separation from the scheduler.

**Comment by Insprill** [comment]
I agree we should implement a tick system, but we also must be careful to draw the line somewhere for what we simulate to avoid becoming an entire server or having unexpected behavior because some things are simulated and others aren't. That's definitely something for MB 4 though.

**Review by Thorinwasher — APPROVED** [review]
Looks good to me

**Comment by thelooter** [comment]
> I agree we should implement a tick system, but we also must be careful to draw the line somewhere for what we simulate to avoid becoming an entire server or having unexpected behavior because some things are simulated and others aren't. That's definitely something for MB 4 though.

Can you make an issue for this?

**Review by thelooter — APPROVED** [review]

**Pull request merged**
