### PR TITLE
Implemented EnchantmentMock.canEnchantItem() for vanilla enchantments

### PR DESCRIPTION
**Pull request by Braekpo1nt**
# Description
- Added `Set<NamespacedKey> enchantables` to `EnchantmentMock` 
- Implemented constructors and `from(JsonObject)` to assign values to the `enchantables` set
- Added `enchantables` lists to `enchantment.json` for use by the `RegistryMock`
  - This is generated by MockBukkit/MetaMiner. [PR 7](https://github.com/MockBukkit/MetaMiner/pull/7) includes the necessary changes to generate this data. 

# Checklist
The following items should be checked before the pull request can be merged.
- [x] Code follows existing style.
- [x] Unit tests added (if applicable).

### CODE REVIEW

**Review by Thorinwasher — COMMENTED** [review]
Looks good to me. About generating files, did you make a script for that? It's necessary to make a pull request for this in MockBukkit/MetaMiner

**Comment by Braekpo1nt** [comment]
@Thorinwasher I was not aware of MockBukkit/MetaMiner, I did not make a script for this I basically did it by hand. I didn't see this in the contributing guide lol that would have been handy.

**Comment by Braekpo1nt** [comment]
@Thorinwasher I have created [PR 7 in MockBukkit/MetaMiner](https://github.com/MockBukkit/MetaMiner/pull/7) to generate the data for this `enchantables` addition.

**Review by Thorinwasher — APPROVED** [review]

**Comment by Thorinwasher** [comment]
>  I did not make a script for this I basically did it by hand.

I feel you, made the same thing as well initially. But just scanning a real server is much faster

**Pull request merged**
