### PR TITLE
Unit tests and fixes for get eye height

### PR DESCRIPTION
**Pull request by 4everTheOne**
# Description
This PR adds unit tests to cover the method getEyeHeight for some of the classes.
During the creation of this tests, i noticed that some behaviors were not properly implemented.

To simplify the review, i would recommend review each commit separated, since it makes it easier to identify what's the class under test.

# Checklist
The following items should be checked before the pull request can be merged.
- [X] Code follows existing style.
- [X] Unit tests added (if applicable).

### CODE REVIEW

**Comment by 4everTheOne** [comment]
The build is failing due to an update in PaperMC, and it also affects the branch v1.21.

From what i could identify, the issue was introduced in build [1.21-R0.1-20240809.202931-130](https://repo.papermc.io/service/rest/repository/browse/maven-public/io/papermc/paper/paper-api/1.21-R0.1-SNAPSHOT/1.21-R0.1-20240809.202931-130/), because build [1.21-R0.1-20240807.125219-129](https://repo.papermc.io/service/rest/repository/browse/maven-public/io/papermc/paper/paper-api/1.21-R0.1-SNAPSHOT/1.21-R0.1-20240807.125219-129/) works as intended.

**Comment by 4everTheOne** [comment]
Validated that PR https://github.com/MockBukkit/MockBukkit/pull/1062 fixes the issue. Waiting for it to be merged

**Comment by thelooter** [comment]
It's merged

**Comment by 4everTheOne** [comment]
> It's merged 

Thank you for the update. PR has been updated.

**Review by Thorinwasher — APPROVED** [review]
All the floating point precision faults breaks my non existing OCD (probably correct though)

Other than that, I would personally have added the hoglin mock into a separate pr. (But this is such a small nitpick I will merge anyhow)

**Pull request merged**
