### PR TITLE
Fix data races in scheduler, plugin manager and player list

### PR DESCRIPTION
**Pull request by frengor**
# Description
This fixes data races and race conditions in the scheduler, plugin manager and player list.

As discussed on Discord, this also makes internal-only methods in `ScheduledTask` and `RepeatingTask` classes `protected` and `@ApiStatus.Internal`.

# Checklist
The following items should be checked before the pull request can be merged.
- [x] Code follows existing style.
- [x] Unit tests added (not really applicable here I think).

### CODE REVIEW

**Comment by frengor** [comment]
~I don't know what's wrong with GitHub Actions.~
Edit: fixed now, thanks!

**Comment by Thorinwasher** [comment]
Looks good to me, just going to wait with this until we completely switch to 4.0.

I'm clueless here, but is there any way to test this. Raceconditions seems from my point of view not possible to test using unit tests

**Comment by frengor** [comment]
> I'm clueless here, but is there any way to test this. Raceconditions seems from my point of view not possible to test using unit tests

I don't think there is any sane way to test it. The best I can think of is to call the methods from a bunch of different threads and hope that if anything's wrong it fails the test &mdash; which may not even happen.

**Comment by thelooter** [comment]
> > I'm clueless here, but is there any way to test this. Raceconditions seems from my point of view not possible to test using unit tests
> 
> I don't think there is any sane way to test it. The best I can think of is to call the methods from a bunch of different threads and hope that if anything's wrong it fails the test — which may not even happen.

You can somewhat test for it by using `@RepeatedTest`

**Comment by frengor** [comment]
> You can somewhat test for it by using `@RepeatedTest`

Yes, but not really IMO. `@RepeatedTest` is basically equivalent to running the tests multiple times manually. It would surely help to try the tests with different scheduling, however that is not the main issue when testing race conditions.

**Comment by Thorinwasher** [comment]
Don't worry about this huge pile of merge issues, you can use the `--onto` flag when rebasing later on

**Comment by Thorinwasher** [comment]
> Yes, but not really IMO. @RepeatedTest is basically equivalent to running the tests multiple times manually. It would surely help to try the tests with different scheduling, however that is not the main issue when testing race conditions

Yeah, it's not a reliable unit test, as race conditions will always have this randomness to it. I agree, this is more for manual testing, where you stress test methods by repeating the same operation thousands of times on two different threads. We could actually possibly make a specialized repository for this, that tests mockbukkit automatically, but with a much larger test-time, like multiple minutes or hours.

**Comment by thelooter** [comment]
We now merged 4.0 into v1.21. Please rebase your branch to the v1.21 state

**Comment by thelooter** [comment]
Please rebase this PR

**Comment by frengor** [comment]
> Please rebase this PR

Done!

**Review by Thorinwasher — APPROVED** [review]

**Pull request merged**
