### PR TITLE
Improved code to getEyeHeight

### PR DESCRIPTION
**Pull request by 4everTheOne**
# Description
This PR's updates the current logic to get eye height, to match the correct values.
The entities width, height and eye height were validated against [Minecraft Wiki](https://minecraft.wiki) and Mojang Source code (net.minecraft.world.entity.EntityType).

# Checklist
The following items should be checked before the pull request can be merged.
- [X] Code follows existing style.
- [X] Unit tests added (if applicable).

### CODE REVIEW

**Comment by 4everTheOne** [comment]
Sorry for the PR size, but there's a lot of entities in the project.
I tried to split de work in commit to make it easier to review.

**Comment by Thorinwasher** [comment]
I know you put a lot of work filling in those json files (I wasted one day on the initial commit for these files), would it be possible to add this to metaminer?

**Comment by 4everTheOne** [comment]
I will try to add it there, but i will need some time to get used to this.
Is it possible to access Mojang classes directly from there? To do this i mined in paper project and had to access mojang EntityType.

Is it possible to do it in MetaMiner? If so, i can implement it, i still have the code for it.

**Comment by 4everTheOne** [comment]
> I will try to add it there, but i will need some time to get used to this. Is it possible to access Mojang classes directly from there? To do this i mined in paper project and had to access mojang EntityType.
> 
> Is it possible to do it in MetaMiner? If so, i can implement it, i still have the code for it.

It's possible, i did a quick test to copy and paste the code from paper directly to it and it worked.
I'll improve the code and open a PR for it.

**Comment by 4everTheOne** [comment]
At the moment i have it working for the default state only. It's really hard to automate this steps for other sub-types such as baby, small, medium, big, ...
The main problem is that this values are not stored in the entity type. They are stored in the entity, in _BABY_DIMENSIONS_ and _BABY_SCALE_. I tried to use reflection to retrieve this information, but mapping the entity type to the real entity in the Mojang has been a difficult task.
Should I open a PR as draft containing the current code?

**Comment by Thorinwasher** [comment]
> It's really hard to automate this steps for other sub-types such as baby, small, medium, big

Ah, I can give it a go when I have the time then. Could probably be done using reflection

**Comment by Thorinwasher** [comment]
> Should I open a PR as draft containing the current code?

Sure, do that

**Review by Thorinwasher — APPROVED** [review]

**Pull request merged**
